version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "80:80"  
    environment:
      - NODE_ENV=development
      - DB_HOST=backend 
      - DB_USER=todo
      - DB_PASSWORD=todo
      - DB_NAME=todo
    volumes:
      - ./backend:/app 
      - /app/node_modules  
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app  
      - /app/node_modules
    depends_on:
      - backend

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql  # Volume persistant pour les données MySQL
    ports:
      - "3306:3306"  # Expose MySQL sur le port 3306

volumes:
  mysql-data:
    driver: local
